"""initial schema

Revision ID: 1fc70f5694c1
Revises: 
Create Date: 2026-07-29 17:03:41.368699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fc70f5694c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalias_aceptadas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('so_id', sa.String(), nullable=False),
    sa.Column('motivo', sa.String(), server_default='', nullable=False),
    sa.Column('aceptado_por', sa.String(), server_default='', nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalias_aceptadas_so_id'), 'anomalias_aceptadas', ['so_id'], unique=False)
    op.create_table('app_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('bandeja_auditoria',
    sa.Column('audit_id', sa.String(), nullable=False),
    sa.Column('so_id', sa.String(), nullable=False),
    sa.Column('tipo_auditoria', sa.String(), server_default='', nullable=False),
    sa.Column('motor_calcula_usd', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('odoo_registrado_usd', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('diferencia_usd', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('detalle_odoo', sa.Text(), server_default='', nullable=False),
    sa.Column('detalle_motor', sa.Text(), server_default='', nullable=False),
    sa.Column('estado', sa.String(), server_default='', nullable=False),
    sa.Column('revisado_por', sa.String(), nullable=True),
    sa.Column('timestamp_audit', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_bandeja_auditoria_so_id'), 'bandeja_auditoria', ['so_id'], unique=False)
    op.create_table('clientes',
    sa.Column('cliente_id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('vendedor_email', sa.String(), server_default='', nullable=False),
    sa.Column('wh_iva_agent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('wh_iva_rate', sa.Numeric(precision=7, scale=4), server_default='75.0', nullable=False),
    sa.PrimaryKeyConstraint('cliente_id')
    )
    op.create_table('descuento_bcv_completo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vigencia_desde')
    )
    op.create_table('descuentos_diferencial_cambiario',
    sa.Column('regla_id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), server_default='', nullable=False),
    sa.Column('tipo_diferencial', sa.String(), server_default='fijo_35_ves_usd', nullable=False),
    sa.Column('tipo_calculo', sa.String(), server_default='fijo', nullable=False),
    sa.Column('porcentaje_fijo', sa.Numeric(precision=7, scale=4), server_default='0.35', nullable=False),
    sa.Column('marca', sa.String(), server_default='*', nullable=False),
    sa.Column('categoria', sa.String(), server_default='*', nullable=False),
    sa.Column('min_cantidad', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('max_cantidad', sa.Numeric(precision=18, scale=4), server_default='999999', nullable=False),
    sa.Column('unidad_medida', sa.String(), server_default='USD', nullable=False),
    sa.Column('tipo_beneficio', sa.String(), server_default='descuento', nullable=False),
    sa.Column('monedas_aplicables', sa.String(), server_default='*', nullable=False),
    sa.Column('listas_aplicables', sa.String(), server_default='*', nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=False),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('regla_id')
    )
    op.create_table('descuentos_producto',
    sa.Column('regla_id', sa.String(), nullable=False),
    sa.Column('productos', sa.String(), server_default='*', nullable=False),
    sa.Column('marca', sa.String(), server_default='*', nullable=False),
    sa.Column('categoria', sa.String(), server_default='*', nullable=False),
    sa.Column('min_cantidad', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('max_cantidad', sa.Numeric(precision=18, scale=4), server_default='999999', nullable=False),
    sa.Column('unidad_medida', sa.String(), server_default='CAJAS', nullable=False),
    sa.Column('tipo_beneficio', sa.String(), server_default='descuento', nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=7, scale=4), server_default='0.05', nullable=False),
    sa.Column('monedas_aplicables', sa.String(), server_default='*', nullable=False),
    sa.Column('listas_aplicables', sa.String(), server_default='*', nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=False),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('regla_id')
    )
    op.create_table('descuentos_pronto_pago',
    sa.Column('regla_id', sa.String(), nullable=False),
    sa.Column('marca', sa.String(), server_default='*', nullable=False),
    sa.Column('categoria', sa.String(), server_default='*', nullable=False),
    sa.Column('min_cantidad', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('max_cantidad', sa.Numeric(precision=18, scale=4), server_default='999999', nullable=False),
    sa.Column('unidad_medida', sa.String(), server_default='USD', nullable=False),
    sa.Column('tipo_beneficio', sa.String(), server_default='descuento', nullable=False),
    sa.Column('dias_gracia', sa.Integer(), server_default='3', nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=7, scale=4), server_default='0.05', nullable=False),
    sa.Column('monedas_aplicables', sa.String(), server_default='*', nullable=False),
    sa.Column('listas_aplicables', sa.String(), server_default='*', nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=False),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('tipo_descuento', sa.String(), server_default='contado', nullable=False),
    sa.PrimaryKeyConstraint('regla_id')
    )
    op.create_table('descuentos_recompra',
    sa.Column('regla_id', sa.String(), nullable=False),
    sa.Column('marca', sa.String(), server_default='GLOBAL OIL', nullable=False),
    sa.Column('categoria', sa.String(), server_default='CAJA', nullable=False),
    sa.Column('min_cajas', sa.Integer(), server_default='2', nullable=False),
    sa.Column('max_cajas', sa.Integer(), server_default='4', nullable=False),
    sa.Column('min_cantidad', sa.Numeric(precision=18, scale=4), server_default='2', nullable=False),
    sa.Column('max_cantidad', sa.Numeric(precision=18, scale=4), server_default='4', nullable=False),
    sa.Column('unidad_medida', sa.String(), server_default='CAJAS', nullable=False),
    sa.Column('tipo_beneficio', sa.String(), server_default='descuento', nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=7, scale=4), server_default='0.03', nullable=False),
    sa.Column('max_usos_mes', sa.Integer(), server_default='1', nullable=False),
    sa.Column('dias_ventana', sa.Integer(), server_default='30', nullable=False),
    sa.Column('listas_aplicables', sa.String(), server_default='*', nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=False),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('regla_id')
    )
    op.create_table('descuentos_volumen',
    sa.Column('regla_id', sa.String(), nullable=False),
    sa.Column('marca', sa.String(), server_default='*', nullable=False),
    sa.Column('categoria', sa.String(), server_default='*', nullable=False),
    sa.Column('litros_minimo', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=7, scale=4), server_default='0.05', nullable=False),
    sa.Column('min_cantidad', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('max_cantidad', sa.Numeric(precision=18, scale=4), server_default='999999', nullable=False),
    sa.Column('unidad_medida', sa.String(), server_default='UNIDADES', nullable=False),
    sa.Column('tipo_beneficio', sa.String(), server_default='descuento', nullable=False),
    sa.Column('tipo_evaluacion', sa.String(), server_default='orden', nullable=False),
    sa.Column('dias_evaluacion', sa.Integer(), server_default='30', nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=False),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.Column('listas_aplicables', sa.String(), server_default='*', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('regla_id')
    )
    op.create_table('exclusiones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('regla_tipo_a', sa.String(), nullable=False),
    sa.Column('regla_tipo_b', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('regla_tipo_a', 'regla_tipo_b', name='uq_exclusiones_par')
    )
    op.create_table('fechas_historicas',
    sa.Column('so_id', sa.String(), nullable=False),
    sa.Column('fecha_historica', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('so_id')
    )
    op.create_table('feriados',
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.String(), server_default='', nullable=False),
    sa.Column('tipo', sa.Enum('nacional', 'regional', 'bancario', name='tipo_feriado'), nullable=False),
    sa.PrimaryKeyConstraint('fecha')
    )
    op.create_table('listas_precios_historicas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.String(), nullable=False),
    sa.Column('lista_precios', sa.String(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=True),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listas_precios_historicas_producto_id'), 'listas_precios_historicas', ['producto_id'], unique=False)
    op.create_table('metodos_pago',
    sa.Column('metodo_id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('moneda', sa.Enum('USD', 'VES', name='moneda'), nullable=False),
    sa.Column('tipo_tasa', sa.Enum('BCV', 'Binance', 'N_A', name='tipo_tasa'), nullable=False),
    sa.Column('es_contado', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('metodo_id')
    )
    op.create_table('promocion_primera_compra',
    sa.Column('regla_id', sa.String(), nullable=False),
    sa.Column('tipo_beneficio', sa.String(), server_default='producto', nullable=False),
    sa.Column('productos', sa.String(), server_default='', nullable=False),
    sa.Column('valor', sa.Numeric(precision=18, scale=4), server_default='1', nullable=False),
    sa.Column('compra_minima', sa.Numeric(precision=18, scale=4), server_default='3', nullable=False),
    sa.Column('regalo_tipo', sa.String(), server_default='solo_uno', nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=False),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.Column('descuento_fallback', sa.Numeric(precision=7, scale=4), server_default='0.02', nullable=False),
    sa.Column('categorias_aplica', sa.String(), server_default='Comercial', nullable=False),
    sa.Column('marca', sa.String(), server_default='GLOBAL OIL', nullable=False),
    sa.Column('categoria', sa.String(), server_default='CAJA', nullable=False),
    sa.Column('min_cantidad', sa.Numeric(precision=18, scale=4), server_default='3', nullable=False),
    sa.Column('max_cantidad', sa.Numeric(precision=18, scale=4), server_default='999999', nullable=False),
    sa.Column('unidad_medida', sa.String(), server_default='CAJAS', nullable=False),
    sa.Column('listas_aplicables', sa.String(), server_default='*', nullable=False),
    sa.Column('solo_primera_compra', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('regla_id')
    )
    op.create_table('reglas_recurrencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('condicion', sa.Enum('primera_compra', 'recompra', name='condicion'), nullable=False),
    sa.Column('tipo_beneficio', sa.Enum('nota_credito', 'porcentaje', name='tipo_beneficio_regla'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=False),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serie_tasas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('tasa_bcv', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('tasa_binance', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('fuente', sa.String(), server_default='', nullable=False),
    sa.Column('es_heredada', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('capturada_ok', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('tasa_binance_manana', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('tasa_binance_tarde', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('tasa_binance_diario', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('diferencial_bcv_binance_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('tasa_bcv_euro', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serie_tasas_timestamp'), 'serie_tasas', ['timestamp'], unique=False)
    op.create_table('tasas_historicas_auditoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('campo', sa.String(), server_default='', nullable=False),
    sa.Column('valor_anterior', sa.String(), nullable=True),
    sa.Column('valor_nuevo', sa.String(), nullable=True),
    sa.Column('editado_por', sa.String(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios_plataforma',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), server_default='', nullable=False),
    sa.Column('rol', sa.String(), server_default='', nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('ordenes_venta',
    sa.Column('so_id', sa.String(), nullable=False),
    sa.Column('cliente_id', sa.String(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('fecha_entrega', sa.Date(), nullable=True),
    sa.Column('monto_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('lista_precios', sa.String(), server_default='', nullable=False),
    sa.Column('vendedor_email', sa.String(), server_default='', nullable=False),
    sa.Column('es_primera_compra', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('facturada', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('factura_id', sa.String(), nullable=True),
    sa.Column('monto_facturado', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('estado_orden', sa.String(), server_default='sale', nullable=False),
    sa.Column('estado_entrega', sa.String(), server_default='', nullable=False),
    sa.Column('entregada_completa', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tiene_devolucion', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.cliente_id'], ),
    sa.PrimaryKeyConstraint('so_id')
    )
    op.create_index(op.f('ix_ordenes_venta_cliente_id'), 'ordenes_venta', ['cliente_id'], unique=False)
    op.create_table('pagos',
    sa.Column('pago_id', sa.String(), nullable=False),
    sa.Column('cliente_id', sa.String(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('moneda', sa.Enum('USD', 'VES', name='moneda'), nullable=False),
    sa.Column('metodo_pago', sa.String(), server_default='', nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=False),
    sa.Column('vendedor_email', sa.String(), server_default='', nullable=False),
    sa.Column('recibido', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('numero_recibido', sa.String(), nullable=True),
    sa.Column('fecha_recibido', sa.DateTime(), nullable=True),
    sa.Column('recibido_por', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.cliente_id'], ),
    sa.PrimaryKeyConstraint('pago_id')
    )
    op.create_index(op.f('ix_pagos_cliente_id'), 'pagos', ['cliente_id'], unique=False)
    op.create_table('bandeja_facturacion',
    sa.Column('so_id', sa.String(), nullable=False),
    sa.Column('lista_aplicada', sa.String(), server_default='', nullable=False),
    sa.Column('precio_base_calculado', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_descuentos', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('ncs_calculadas', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('total_motor', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('requiere_revision', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('candidata_a_cierre', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('aprobado_por', sa.String(), nullable=True),
    sa.Column('estado', sa.Enum('calculado', 'aprobado', 'facturado', name='estado_bandeja'), server_default='calculado', nullable=False),
    sa.ForeignKeyConstraint(['so_id'], ['ordenes_venta.so_id'], ),
    sa.PrimaryKeyConstraint('so_id')
    )
    op.create_table('conciliacion',
    sa.Column('so_id', sa.String(), nullable=False),
    sa.Column('total_motor', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('monto_odoo', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('ncs_odoo', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('diferencia', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('resultado', sa.Enum('verde', 'amarillo', 'rojo', name='resultado_conciliacion'), nullable=False),
    sa.Column('revisado_por', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['so_id'], ['ordenes_venta.so_id'], ),
    sa.PrimaryKeyConstraint('so_id')
    )
    op.create_table('lineas_orden',
    sa.Column('linea_id', sa.String(), nullable=False),
    sa.Column('so_id', sa.String(), nullable=False),
    sa.Column('producto', sa.String(), server_default='', nullable=False),
    sa.Column('marca', sa.String(), server_default='', nullable=False),
    sa.Column('categoria', sa.String(), server_default='', nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cantidad_entregada', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('descuento', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['so_id'], ['ordenes_venta.so_id'], ),
    sa.PrimaryKeyConstraint('linea_id')
    )
    op.create_index(op.f('ix_lineas_orden_so_id'), 'lineas_orden', ['so_id'], unique=False)
    op.create_table('vinculaciones',
    sa.Column('vinc_id', sa.String(), nullable=False),
    sa.Column('pago_id', sa.String(), nullable=False),
    sa.Column('so_id', sa.String(), nullable=False),
    sa.Column('monto_aplicado', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('hora_pago_confirmada', sa.DateTime(), nullable=False),
    sa.Column('tasa_bcv_aplicada', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('tasa_binance_aplicada', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('es_tasa_heredada', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('equiv_usd_bcv', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('equiv_usd_binance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('equiv_ves_bcv', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('equiv_ves_binance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('confirmado_por', sa.String(), server_default='', nullable=False),
    sa.Column('timestamp_registro', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'aprobado', 'facturado', 'conciliado', name='estado_vinculacion'), server_default='pendiente', nullable=False),
    sa.Column('moneda_abono', sa.Enum('USD', 'VES', name='moneda'), server_default='VES', nullable=False),
    sa.Column('tipo_tasa_abono', sa.Enum('BCV', 'Binance', 'N_A', name='tipo_tasa'), server_default='N_A', nullable=False),
    sa.Column('bcv_variante', sa.String(), server_default='USD', nullable=False),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos.pago_id'], ),
    sa.ForeignKeyConstraint(['so_id'], ['ordenes_venta.so_id'], ),
    sa.PrimaryKeyConstraint('vinc_id')
    )
    op.create_index(op.f('ix_vinculaciones_pago_id'), 'vinculaciones', ['pago_id'], unique=False)
    op.create_index(op.f('ix_vinculaciones_so_id'), 'vinculaciones', ['so_id'], unique=False)
    op.create_table('descuento_aplicado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('so_id', sa.String(), nullable=False),
    sa.Column('origen', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), server_default='', nullable=False),
    sa.Column('monto', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['so_id'], ['bandeja_facturacion.so_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_descuento_aplicado_so_id'), 'descuento_aplicado', ['so_id'], unique=False)
    # ### end Alembic commands ###

    # serie_tasas es auditoria inmutable (append-only) -- "el sync NUNCA la
    # toca" es hoy solo una convencion de codigo (repositories.py). Un
    # trigger lo hace real a nivel de base de datos, sin depender de que la
    # conexion de la app use un rol Postgres restringido (Railway da un solo
    # rol con permisos completos para el addon de Postgres, no roles
    # separados por defecto -- el trigger funciona igual sin importar quien
    # se conecte).
    op.execute(
        """
        CREATE OR REPLACE FUNCTION serie_tasas_append_only() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'serie_tasas es append-only: % no esta permitido', TG_OP;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER serie_tasas_no_update_delete
        BEFORE UPDATE OR DELETE ON serie_tasas
        FOR EACH ROW EXECUTE FUNCTION serie_tasas_append_only();
        """
    )


def downgrade() -> None:
    # El trigger se elimina automaticamente al hacer DROP TABLE serie_tasas
    # (mas abajo); la funcion es un objeto aparte y sí necesita limpieza.
    op.execute("DROP FUNCTION IF EXISTS serie_tasas_append_only() CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_descuento_aplicado_so_id'), table_name='descuento_aplicado')
    op.drop_table('descuento_aplicado')
    op.drop_index(op.f('ix_vinculaciones_so_id'), table_name='vinculaciones')
    op.drop_index(op.f('ix_vinculaciones_pago_id'), table_name='vinculaciones')
    op.drop_table('vinculaciones')
    op.drop_index(op.f('ix_lineas_orden_so_id'), table_name='lineas_orden')
    op.drop_table('lineas_orden')
    op.drop_table('conciliacion')
    op.drop_table('bandeja_facturacion')
    op.drop_index(op.f('ix_pagos_cliente_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_ordenes_venta_cliente_id'), table_name='ordenes_venta')
    op.drop_table('ordenes_venta')
    op.drop_table('usuarios_plataforma')
    op.drop_table('tasas_historicas_auditoria')
    op.drop_index(op.f('ix_serie_tasas_timestamp'), table_name='serie_tasas')
    op.drop_table('serie_tasas')
    op.drop_table('reglas_recurrencia')
    op.drop_table('promocion_primera_compra')
    op.drop_table('metodos_pago')
    op.drop_index(op.f('ix_listas_precios_historicas_producto_id'), table_name='listas_precios_historicas')
    op.drop_table('listas_precios_historicas')
    op.drop_table('feriados')
    op.drop_table('fechas_historicas')
    op.drop_table('exclusiones')
    op.drop_table('descuentos_volumen')
    op.drop_table('descuentos_recompra')
    op.drop_table('descuentos_pronto_pago')
    op.drop_table('descuentos_producto')
    op.drop_table('descuentos_diferencial_cambiario')
    op.drop_table('descuento_bcv_completo')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_bandeja_auditoria_so_id'), table_name='bandeja_auditoria')
    op.drop_table('bandeja_auditoria')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_anomalias_aceptadas_so_id'), table_name='anomalias_aceptadas')
    op.drop_table('anomalias_aceptadas')
    # ### end Alembic commands ###

    # op.drop_table() no elimina los ENUM nativos que crea (podrian estar
    # compartidos entre tablas) -- sin esto, un downgrade seguido de un
    # upgrade falla con "type ... already exists".
    for enum_name in (
        "moneda",
        "tipo_tasa",
        "condicion",
        "tipo_beneficio_regla",
        "tipo_feriado",
        "estado_vinculacion",
        "estado_bandeja",
        "resultado_conciliacion",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
