"""corrige columnas reales de usuarios_plataforma, anomalias_aceptadas, tasas_historicas_auditoria y listas_precios_historicas

Revision ID: bae0a067b349
Revises: 1fc70f5694c1
Create Date: 2026-07-29 18:01:18.794222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bae0a067b349'
down_revision: Union[str, None] = '1fc70f5694c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anomalias_aceptadas', sa.Column('anomalia_id', sa.String(), nullable=False))
    op.add_column('anomalias_aceptadas', sa.Column('factura_id', sa.String(), server_default='', nullable=False))
    op.add_column('anomalias_aceptadas', sa.Column('tipo_anomalia', sa.String(), server_default='', nullable=False))
    op.add_column('anomalias_aceptadas', sa.Column('motivo_aceptacion', sa.String(), server_default='', nullable=False))
    op.add_column('anomalias_aceptadas', sa.Column('aprobado_por', sa.String(), server_default='', nullable=False))
    op.add_column('anomalias_aceptadas', sa.Column('timestamp_aprobacion', sa.DateTime(), nullable=True))
    op.drop_column('anomalias_aceptadas', 'id')
    op.drop_column('anomalias_aceptadas', 'aceptado_por')
    op.drop_column('anomalias_aceptadas', 'motivo')
    op.drop_column('anomalias_aceptadas', 'timestamp')
    # autogenerate no detecta el cambio de PK (id autoincrement -> anomalia_id
    # natural): dropear la columna 'id' ya tira la PK vieja, hace falta crear
    # la nueva a mano.
    op.create_primary_key('pk_anomalias_aceptadas', 'anomalias_aceptadas', ['anomalia_id'])
    op.add_column('listas_precios_historicas', sa.Column('codigo', sa.String(), nullable=False))
    op.add_column('listas_precios_historicas', sa.Column('producto_nombre', sa.String(), server_default='', nullable=False))
    op.add_column('listas_precios_historicas', sa.Column('precio_usd', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('listas_precios_historicas', sa.Column('precio_bcv_euro', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('listas_precios_historicas', sa.Column('fecha_corte', sa.Date(), nullable=True))
    op.add_column('listas_precios_historicas', sa.Column('notas', sa.Text(), server_default='', nullable=False))
    op.drop_index('ix_listas_precios_historicas_producto_id', table_name='listas_precios_historicas')
    op.create_index(op.f('ix_listas_precios_historicas_codigo'), 'listas_precios_historicas', ['codigo'], unique=False)
    op.drop_column('listas_precios_historicas', 'vigencia_desde')
    op.drop_column('listas_precios_historicas', 'vigencia_hasta')
    op.drop_column('listas_precios_historicas', 'producto_id')
    op.drop_column('listas_precios_historicas', 'lista_precios')
    op.drop_column('listas_precios_historicas', 'precio')
    op.add_column('tasas_historicas_auditoria', sa.Column('fecha', sa.Date(), nullable=False))
    op.add_column('tasas_historicas_auditoria', sa.Column('tasa_bcv_usd', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('tasas_historicas_auditoria', sa.Column('tasa_bcv_euro', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('tasas_historicas_auditoria', sa.Column('tasa_binance_promedio_diario', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('tasas_historicas_auditoria', sa.Column('diferencial_bcv_binance_pct', sa.String(), nullable=True))
    op.add_column('tasas_historicas_auditoria', sa.Column('fuente', sa.String(), server_default='', nullable=False))
    op.add_column('tasas_historicas_auditoria', sa.Column('notas', sa.Text(), server_default='', nullable=False))
    op.create_unique_constraint(
        'uq_tasas_historicas_auditoria_fecha', 'tasas_historicas_auditoria', ['fecha']
    )
    op.drop_column('tasas_historicas_auditoria', 'valor_nuevo')
    op.drop_column('tasas_historicas_auditoria', 'editado_por')
    op.drop_column('tasas_historicas_auditoria', 'campo')
    op.drop_column('tasas_historicas_auditoria', 'valor_anterior')
    op.drop_column('tasas_historicas_auditoria', 'timestamp')
    op.add_column('usuarios_plataforma', sa.Column('nombre_odoo', sa.String(), server_default='', nullable=False))
    op.add_column('usuarios_plataforma', sa.Column('salt', sa.String(), nullable=True))
    op.add_column('usuarios_plataforma', sa.Column('activo', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('usuarios_plataforma', sa.Column('fecha_registro', sa.DateTime(), nullable=True))
    op.drop_column('usuarios_plataforma', 'nombre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios_plataforma', sa.Column('nombre', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.drop_column('usuarios_plataforma', 'fecha_registro')
    op.drop_column('usuarios_plataforma', 'activo')
    op.drop_column('usuarios_plataforma', 'salt')
    op.drop_column('usuarios_plataforma', 'nombre_odoo')
    op.add_column('tasas_historicas_auditoria', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('tasas_historicas_auditoria', sa.Column('valor_anterior', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tasas_historicas_auditoria', sa.Column('campo', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('tasas_historicas_auditoria', sa.Column('editado_por', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('tasas_historicas_auditoria', sa.Column('valor_nuevo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(
        'uq_tasas_historicas_auditoria_fecha', 'tasas_historicas_auditoria', type_='unique'
    )
    op.drop_column('tasas_historicas_auditoria', 'notas')
    op.drop_column('tasas_historicas_auditoria', 'fuente')
    op.drop_column('tasas_historicas_auditoria', 'diferencial_bcv_binance_pct')
    op.drop_column('tasas_historicas_auditoria', 'tasa_binance_promedio_diario')
    op.drop_column('tasas_historicas_auditoria', 'tasa_bcv_euro')
    op.drop_column('tasas_historicas_auditoria', 'tasa_bcv_usd')
    op.drop_column('tasas_historicas_auditoria', 'fecha')
    op.add_column('listas_precios_historicas', sa.Column('precio', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False))
    op.add_column('listas_precios_historicas', sa.Column('lista_precios', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('listas_precios_historicas', sa.Column('producto_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('listas_precios_historicas', sa.Column('vigencia_hasta', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('listas_precios_historicas', sa.Column('vigencia_desde', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_listas_precios_historicas_codigo'), table_name='listas_precios_historicas')
    op.create_index('ix_listas_precios_historicas_producto_id', 'listas_precios_historicas', ['producto_id'], unique=False)
    op.drop_column('listas_precios_historicas', 'notas')
    op.drop_column('listas_precios_historicas', 'fecha_corte')
    op.drop_column('listas_precios_historicas', 'precio_bcv_euro')
    op.drop_column('listas_precios_historicas', 'precio_usd')
    op.drop_column('listas_precios_historicas', 'producto_nombre')
    op.drop_column('listas_precios_historicas', 'codigo')
    op.add_column('anomalias_aceptadas', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('anomalias_aceptadas', sa.Column('motivo', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('anomalias_aceptadas', sa.Column('aceptado_por', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint('pk_anomalias_aceptadas', 'anomalias_aceptadas', type_='primary')
    op.add_column('anomalias_aceptadas', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_primary_key('pk_anomalias_aceptadas', 'anomalias_aceptadas', ['id'])
    op.drop_column('anomalias_aceptadas', 'timestamp_aprobacion')
    op.drop_column('anomalias_aceptadas', 'aprobado_por')
    op.drop_column('anomalias_aceptadas', 'motivo_aceptacion')
    op.drop_column('anomalias_aceptadas', 'tipo_anomalia')
    op.drop_column('anomalias_aceptadas', 'factura_id')
    op.drop_column('anomalias_aceptadas', 'anomalia_id')
    # ### end Alembic commands ###
